// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   cm2715@EEWS104A-016
//  Generated date: Wed May 04 15:22:19 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    Render_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module Render_core_fsm (
  clk, rst, fsm_output
);
  input clk;
  input rst;
  output [1:0] fsm_output;
  reg [1:0] fsm_output;


  // FSM State Type Declaration for Render_core_fsm_1
  parameter
    st_main = 1'd0,
    st_main_1 = 1'd1,
    state_x = 1'b0;

  reg [0:0] state_var;
  reg [0:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : Render_core_fsm_1
    case (state_var)
      st_main : begin
        fsm_output = 2'b1;
        state_var_NS = st_main_1;
      end
      st_main_1 : begin
        fsm_output = 2'b10;
        state_var_NS = st_main;
      end
      default : begin
        fsm_output = 2'b00;
        state_var_NS = st_main;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( rst ) begin
      state_var <= st_main;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    Render_core
// ------------------------------------------------------------------


module Render_core (
  clk, rst, X_pix_rsc_mgc_in_wire_d, Y_pix_rsc_mgc_in_wire_d, v_out_rsc_mgc_out_stdreg_d
);
  input clk;
  input rst;
  input [10:0] X_pix_rsc_mgc_in_wire_d;
  input [10:0] Y_pix_rsc_mgc_in_wire_d;
  output [11:0] v_out_rsc_mgc_out_stdreg_d;
  reg [11:0] v_out_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations
  wire [1:0] fsm_output;
  wire C3443_12_dfmergedata_sg3_lpi_dfm_1;
  wire [11:0] aif_3_acc_1_itm;
  wire [12:0] nl_aif_3_acc_1_itm;
  wire [10:0] if_acc_3_itm;
  wire [11:0] nl_if_acc_3_itm;
  wire [11:0] aif_5_acc_1_itm;
  wire [12:0] nl_aif_5_acc_1_itm;
  wire [10:0] if_acc_itm;
  wire [11:0] nl_if_acc_itm;


  // Interconnect Declarations for Component Instantiations 
  Render_core_fsm Render_core_fsm_inst (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output)
    );
  assign C3443_12_dfmergedata_sg3_lpi_dfm_1 = (~((aif_3_acc_1_itm[11]) | (if_acc_3_itm[10])
      | (readslicef_11_1_10((({1'b1 , (~ (X_pix_rsc_mgc_in_wire_d[10:1]))}) + 11'b100111001)))
      | (if_acc_itm[10]))) | (~((aif_3_acc_1_itm[11]) | (if_acc_3_itm[10]) | (aif_5_acc_1_itm[11])
      | (readslicef_12_1_11((conv_u2s_11_12(X_pix_rsc_mgc_in_wire_d) + 12'b110101110001)))))
      | (~((readslicef_12_1_11((({1'b1 , (~ Y_pix_rsc_mgc_in_wire_d)}) + 12'b1111100011)))
      | (readslicef_11_1_10((conv_u2u_10_11(Y_pix_rsc_mgc_in_wire_d[10:1]) + 11'b11100110001)))
      | (aif_5_acc_1_itm[11]) | (if_acc_itm[10])));
  assign nl_aif_3_acc_1_itm = ({1'b1 , (~ Y_pix_rsc_mgc_in_wire_d)}) + 12'b101100011;
  assign aif_3_acc_1_itm = nl_aif_3_acc_1_itm[11:0];
  assign nl_if_acc_3_itm = conv_u2u_10_11(Y_pix_rsc_mgc_in_wire_d[10:1]) + 11'b11111110001;
  assign if_acc_3_itm = nl_if_acc_3_itm[10:0];
  assign nl_aif_5_acc_1_itm = ({1'b1 , (~ X_pix_rsc_mgc_in_wire_d)}) + 12'b10011100011;
  assign aif_5_acc_1_itm = nl_aif_5_acc_1_itm[11:0];
  assign nl_if_acc_itm = conv_u2u_10_11(X_pix_rsc_mgc_in_wire_d[10:1]) + 11'b11111110001;
  assign if_acc_itm = nl_if_acc_itm[10:0];
  always @(posedge clk) begin
    if ( rst ) begin
      v_out_rsc_mgc_out_stdreg_d <= 12'b0;
    end
    else begin
      v_out_rsc_mgc_out_stdreg_d <= MUX_v_12_2_2({v_out_rsc_mgc_out_stdreg_d , ({2'b11
          , C3443_12_dfmergedata_sg3_lpi_dfm_1 , 1'b1 , C3443_12_dfmergedata_sg3_lpi_dfm_1
          , 3'b111 , ({{1{C3443_12_dfmergedata_sg3_lpi_dfm_1}}, C3443_12_dfmergedata_sg3_lpi_dfm_1})
          , 2'b11})}, fsm_output[0]);
    end
  end

  function [0:0] readslicef_11_1_10;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 10;
    readslicef_11_1_10 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_12_1_11;
    input [11:0] vector;
    reg [11:0] tmp;
  begin
    tmp = vector >> 11;
    readslicef_12_1_11 = tmp[0:0];
  end
  endfunction


  function [11:0] MUX_v_12_2_2;
    input [23:0] inputs;
    input [0:0] sel;
    reg [11:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[23:12];
      end
      1'b1 : begin
        result = inputs[11:0];
      end
      default : begin
        result = inputs[23:12];
      end
    endcase
    MUX_v_12_2_2 = result;
  end
  endfunction


  function signed [11:0] conv_u2s_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2s_11_12 = {1'b0, vector};
  end
  endfunction


  function  [10:0] conv_u2u_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_11 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    Render
//  Generated from file(s):
//    2) $PROJECT_HOME/src/Render.cpp
// ------------------------------------------------------------------


module Render (
  X_pix_rsc_z, Y_pix_rsc_z, v_out_rsc_z, clk, rst
);
  input [10:0] X_pix_rsc_z;
  input [10:0] Y_pix_rsc_z;
  output [11:0] v_out_rsc_z;
  input clk;
  input rst;


  // Interconnect Declarations
  wire [10:0] X_pix_rsc_mgc_in_wire_d;
  wire [10:0] Y_pix_rsc_mgc_in_wire_d;
  wire [11:0] v_out_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(11)) X_pix_rsc_mgc_in_wire (
      .d(X_pix_rsc_mgc_in_wire_d),
      .z(X_pix_rsc_z)
    );
  mgc_in_wire #(.rscid(2),
  .width(11)) Y_pix_rsc_mgc_in_wire (
      .d(Y_pix_rsc_mgc_in_wire_d),
      .z(Y_pix_rsc_z)
    );
  mgc_out_stdreg #(.rscid(3),
  .width(12)) v_out_rsc_mgc_out_stdreg (
      .d(v_out_rsc_mgc_out_stdreg_d),
      .z(v_out_rsc_z)
    );
  Render_core Render_core_inst (
      .clk(clk),
      .rst(rst),
      .X_pix_rsc_mgc_in_wire_d(X_pix_rsc_mgc_in_wire_d),
      .Y_pix_rsc_mgc_in_wire_d(Y_pix_rsc_mgc_in_wire_d),
      .v_out_rsc_mgc_out_stdreg_d(v_out_rsc_mgc_out_stdreg_d)
    );
endmodule



