// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   kjr115@EEWS104A-013
//  Generated date: Fri Apr 29 16:20:24 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    Render_core
// ------------------------------------------------------------------


module Render_core (
  clk, rst, v_out_rsc_mgc_out_stdreg_d
);
  input clk;
  input rst;
  output [11:0] v_out_rsc_mgc_out_stdreg_d;
  reg [11:0] v_out_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg [18:0] for_i_1_sva;
    reg [6:0] acc_imod_sva;
    reg [4:0] acc_imod_1_sva;
    reg [3:0] for_acc_2_cse_sva;
    reg [18:0] for_i_1_sva_1;
    reg for_slc_itm;

    begin : mainExit
      forever begin : main
        // C-Step 0 of Loop 'main'
        for_i_1_sva = 19'b0;
        begin : waitLoop0Exit
          forever begin : waitLoop0
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop0Exit;
          end
        end
        // C-Step 1 of Loop 'main'
        begin : for_0Exit
          forever begin : for_0
            // C-Step 0 of Loop 'for_0'
            begin : waitLoop1Exit
              forever begin : waitLoop1
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop1Exit;
              end
            end
            // C-Step 1 of Loop 'for_0'
            acc_imod_sva = conv_s2s_6_7(({3'b100 , (for_i_1_sva[2:0])}) + conv_u2s_5_6(conv_u2u_4_5(readslicef_5_4_1((conv_u2u_4_5({(for_i_1_sva[6:4])
                , 1'b1}) + conv_u2u_4_5(for_i_1_sva[10:7])))) + conv_u2u_4_5(readslicef_5_4_1((conv_u2u_4_5({(for_i_1_sva[14:12])
                , 1'b1}) + conv_u2u_4_5({(for_i_1_sva[18:16]) , (for_i_1_sva[3])}))))))
                + conv_u2s_6_7({(conv_u2u_1_3(~ (for_i_1_sva[3])) + conv_u2u_1_3(~
                (for_i_1_sva[7])) + conv_u2u_1_3(~ (for_i_1_sva[11])) + conv_u2u_1_3(~
                (for_i_1_sva[15]))) , 1'b0 , (conv_u2u_1_2(readslicef_2_1_1((conv_u2u_1_2(for_i_1_sva[15])
                + 2'b1))) + conv_u2u_1_2(readslicef_2_1_1((conv_u2u_1_2(for_i_1_sva[11])
                + 2'b1))))});
            acc_imod_1_sva = (readslicef_6_5_1((conv_u2s_5_6({(~ (acc_imod_sva[3]))
                , 4'b1}) + conv_s2s_4_6(acc_imod_sva[6:3])))) + conv_s2s_4_5({1'b1
                , (acc_imod_sva[2:0])});
            for_acc_2_cse_sva = readslicef_5_4_1((({(acc_imod_1_sva[3:0]) , 1'b1})
                + ({3'b111 , (~ (acc_imod_1_sva[4])) , 1'b1})));
            v_out_rsc_mgc_out_stdreg_d <= {for_acc_2_cse_sva , for_acc_2_cse_sva
                , for_acc_2_cse_sva};
            for_i_1_sva_1 = for_i_1_sva + 19'b1;
            for_slc_itm = readslicef_8_1_7((conv_u2s_7_8(for_i_1_sva_1[18:12]) +
                8'b10110101));
            begin : waitLoop2Exit
              forever begin : waitLoop2
                @(posedge clk);
                if ( rst )
                  disable mainExit;
                if ( clk )
                  disable waitLoop2Exit;
              end
            end
            // C-Step 2 of Loop 'for_0'
            if ( ~ for_slc_itm )
              disable for_0Exit;
            for_i_1_sva = for_i_1_sva_1;
          end
        end
      end
    end
    for_slc_itm = 1'b0;
    for_i_1_sva_1 = 19'b0;
    for_acc_2_cse_sva = 4'b0;
    acc_imod_1_sva = 5'b0;
    acc_imod_sva = 7'b0;
    for_i_1_sva = 19'b0;
    v_out_rsc_mgc_out_stdreg_d <= 12'b0;
  end


  function [3:0] readslicef_5_4_1;
    input [4:0] vector;
    reg [4:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_5_4_1 = tmp[3:0];
  end
  endfunction


  function [0:0] readslicef_2_1_1;
    input [1:0] vector;
    reg [1:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_2_1_1 = tmp[0:0];
  end
  endfunction


  function [4:0] readslicef_6_5_1;
    input [5:0] vector;
    reg [5:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_6_5_1 = tmp[4:0];
  end
  endfunction


  function [0:0] readslicef_8_1_7;
    input [7:0] vector;
    reg [7:0] tmp;
  begin
    tmp = vector >> 7;
    readslicef_8_1_7 = tmp[0:0];
  end
  endfunction


  function signed [6:0] conv_s2s_6_7 ;
    input signed [5:0]  vector ;
  begin
    conv_s2s_6_7 = {vector[5], vector};
  end
  endfunction


  function signed [5:0] conv_u2s_5_6 ;
    input [4:0]  vector ;
  begin
    conv_u2s_5_6 = {1'b0, vector};
  end
  endfunction


  function  [4:0] conv_u2u_4_5 ;
    input [3:0]  vector ;
  begin
    conv_u2u_4_5 = {1'b0, vector};
  end
  endfunction


  function signed [6:0] conv_u2s_6_7 ;
    input [5:0]  vector ;
  begin
    conv_u2s_6_7 = {1'b0, vector};
  end
  endfunction


  function  [2:0] conv_u2u_1_3 ;
    input [0:0]  vector ;
  begin
    conv_u2u_1_3 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [1:0] conv_u2u_1_2 ;
    input [0:0]  vector ;
  begin
    conv_u2u_1_2 = {1'b0, vector};
  end
  endfunction


  function signed [5:0] conv_s2s_4_6 ;
    input signed [3:0]  vector ;
  begin
    conv_s2s_4_6 = {{2{vector[3]}}, vector};
  end
  endfunction


  function signed [4:0] conv_s2s_4_5 ;
    input signed [3:0]  vector ;
  begin
    conv_s2s_4_5 = {vector[3], vector};
  end
  endfunction


  function signed [7:0] conv_u2s_7_8 ;
    input [6:0]  vector ;
  begin
    conv_u2s_7_8 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    Render
//  Generated from file(s):
//    2) $PROJECT_HOME/src/Render.cpp
// ------------------------------------------------------------------


module Render (
  v_out_rsc_z, clk, rst
);
  output [11:0] v_out_rsc_z;
  input clk;
  input rst;


  // Interconnect Declarations
  wire [11:0] v_out_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_out_stdreg #(.rscid(1),
  .width(12)) v_out_rsc_mgc_out_stdreg (
      .d(v_out_rsc_mgc_out_stdreg_d),
      .z(v_out_rsc_z)
    );
  Render_core Render_core_inst (
      .clk(clk),
      .rst(rst),
      .v_out_rsc_mgc_out_stdreg_d(v_out_rsc_mgc_out_stdreg_d)
    );
endmodule



