// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   oh1015@EEWS104A-005
//  Generated date: Thu Apr 28 17:52:21 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    cdt_core
// ------------------------------------------------------------------


module cdt_core (
  clk, arst_n, H_IN_rsc_mgc_in_wire_d, S_IN_rsc_mgc_in_wire_d, V_IN_rsc_mgc_in_wire_d,
      R_OUT_rsc_mgc_out_stdreg_d, B_OUT_rsc_mgc_out_stdreg_d
);
  input clk;
  input arst_n;
  input [9:0] H_IN_rsc_mgc_in_wire_d;
  input [9:0] S_IN_rsc_mgc_in_wire_d;
  input [9:0] V_IN_rsc_mgc_in_wire_d;
  output [9:0] R_OUT_rsc_mgc_out_stdreg_d;
  reg [9:0] R_OUT_rsc_mgc_out_stdreg_d;
  output [9:0] B_OUT_rsc_mgc_out_stdreg_d;
  reg [9:0] B_OUT_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg [9:0] H_IN_1_sva;
    reg [6:0] V_IN_1_sg1_sva;
    reg slc_svs;
    reg land_sva_1;
    reg land_lpi_dfm;
    reg if_slc_svs;
    reg if_lor_sva_1;
    reg if_lor_lpi_dfm;
    reg if_else_slc_svs;
    reg if_else_land_sva_1;

    begin : mainExit
      forever begin : main
        // C-Step 0 of Loop 'main'
        begin : waitLoop0Exit
          forever begin : waitLoop0
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( clk )
              disable waitLoop0Exit;
          end
        end
        // C-Step 1 of Loop 'main'
        if_else_land_sva_1 = 1'b0;
        if_lor_lpi_dfm = 1'b0;
        if_lor_sva_1 = 1'b0;
        land_sva_1 = 1'b0;
        H_IN_1_sva = H_IN_rsc_mgc_in_wire_d;
        V_IN_1_sg1_sva = V_IN_rsc_mgc_in_wire_d[9:3];
        slc_svs = readslicef_10_1_9((conv_u2u_9_10(S_IN_rsc_mgc_in_wire_d[9:1]) +
            10'b1111100111));
        if ( slc_svs ) begin
        end
        else begin
          land_sva_1 = ~ (readslicef_8_1_7((conv_u2u_7_8(V_IN_1_sg1_sva) + 8'b11111011)));
        end
        land_lpi_dfm = land_sva_1 & (~ slc_svs);
        if ( land_lpi_dfm ) begin
          if_slc_svs = readslicef_10_1_9((conv_u2u_9_10(H_IN_1_sva[9:1]) + 10'b1101010001));
          if ( if_slc_svs ) begin
            if_lor_sva_1 = ~ (readslicef_6_1_5((({1'b1 , (~ (H_IN_1_sva[8:4]))})
                + 6'b1)));
          end
          if_lor_lpi_dfm = if_lor_sva_1 | (~ if_slc_svs);
          if ( if_lor_lpi_dfm ) begin
          end
          else begin
            if_else_slc_svs = readslicef_9_1_8((conv_u2u_8_9(H_IN_1_sva[9:2]) + 9'b111010011));
            if ( if_else_slc_svs ) begin
            end
            else begin
              if_else_land_sva_1 = ~ (readslicef_11_1_10((({1'b1 , (~ H_IN_1_sva)})
                  + 11'b100000101)));
            end
          end
        end
        R_OUT_rsc_mgc_out_stdreg_d <= signext_10_1(if_lor_lpi_dfm & land_lpi_dfm);
        B_OUT_rsc_mgc_out_stdreg_d <= signext_10_1(if_else_land_sva_1 & (~ if_else_slc_svs)
            & (~ if_lor_lpi_dfm) & land_lpi_dfm);
      end
    end
    if_else_land_sva_1 = 1'b0;
    if_else_slc_svs = 1'b0;
    if_lor_lpi_dfm = 1'b0;
    if_lor_sva_1 = 1'b0;
    if_slc_svs = 1'b0;
    land_lpi_dfm = 1'b0;
    land_sva_1 = 1'b0;
    slc_svs = 1'b0;
    V_IN_1_sg1_sva = 7'b0;
    H_IN_1_sva = 10'b0;
    B_OUT_rsc_mgc_out_stdreg_d <= 10'b0;
    R_OUT_rsc_mgc_out_stdreg_d <= 10'b0;
  end


  function [0:0] readslicef_10_1_9;
    input [9:0] vector;
    reg [9:0] tmp;
  begin
    tmp = vector >> 9;
    readslicef_10_1_9 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_8_1_7;
    input [7:0] vector;
    reg [7:0] tmp;
  begin
    tmp = vector >> 7;
    readslicef_8_1_7 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_6_1_5;
    input [5:0] vector;
    reg [5:0] tmp;
  begin
    tmp = vector >> 5;
    readslicef_6_1_5 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_9_1_8;
    input [8:0] vector;
    reg [8:0] tmp;
  begin
    tmp = vector >> 8;
    readslicef_9_1_8 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_11_1_10;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 10;
    readslicef_11_1_10 = tmp[0:0];
  end
  endfunction


  function [9:0] signext_10_1;
    input [0:0] vector;
  begin
    signext_10_1= {{9{vector[0]}}, vector};
  end
  endfunction


  function  [9:0] conv_u2u_9_10 ;
    input [8:0]  vector ;
  begin
    conv_u2u_9_10 = {1'b0, vector};
  end
  endfunction


  function  [7:0] conv_u2u_7_8 ;
    input [6:0]  vector ;
  begin
    conv_u2u_7_8 = {1'b0, vector};
  end
  endfunction


  function  [8:0] conv_u2u_8_9 ;
    input [7:0]  vector ;
  begin
    conv_u2u_8_9 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    cdt
//  Generated from file(s):
//    2) $PROJECT_HOME/cdt.cpp
// ------------------------------------------------------------------


module cdt (
  H_IN_rsc_z, S_IN_rsc_z, V_IN_rsc_z, R_OUT_rsc_z, G_OUT_rsc_z, B_OUT_rsc_z, clk,
      arst_n
);
  input [9:0] H_IN_rsc_z;
  input [9:0] S_IN_rsc_z;
  input [9:0] V_IN_rsc_z;
  output [9:0] R_OUT_rsc_z;
  output [9:0] G_OUT_rsc_z;
  output [9:0] B_OUT_rsc_z;
  input clk;
  input arst_n;


  // Interconnect Declarations
  wire [9:0] H_IN_rsc_mgc_in_wire_d;
  wire [9:0] S_IN_rsc_mgc_in_wire_d;
  wire [9:0] V_IN_rsc_mgc_in_wire_d;
  wire [9:0] R_OUT_rsc_mgc_out_stdreg_d;
  wire [9:0] B_OUT_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(10)) H_IN_rsc_mgc_in_wire (
      .d(H_IN_rsc_mgc_in_wire_d),
      .z(H_IN_rsc_z)
    );
  mgc_in_wire #(.rscid(2),
  .width(10)) S_IN_rsc_mgc_in_wire (
      .d(S_IN_rsc_mgc_in_wire_d),
      .z(S_IN_rsc_z)
    );
  mgc_in_wire #(.rscid(3),
  .width(10)) V_IN_rsc_mgc_in_wire (
      .d(V_IN_rsc_mgc_in_wire_d),
      .z(V_IN_rsc_z)
    );
  mgc_out_stdreg #(.rscid(4),
  .width(10)) R_OUT_rsc_mgc_out_stdreg (
      .d(R_OUT_rsc_mgc_out_stdreg_d),
      .z(R_OUT_rsc_z)
    );
  mgc_out_stdreg #(.rscid(5),
  .width(10)) G_OUT_rsc_mgc_out_stdreg (
      .d(10'b0),
      .z(G_OUT_rsc_z)
    );
  mgc_out_stdreg #(.rscid(6),
  .width(10)) B_OUT_rsc_mgc_out_stdreg (
      .d(B_OUT_rsc_mgc_out_stdreg_d),
      .z(B_OUT_rsc_z)
    );
  cdt_core cdt_core_inst (
      .clk(clk),
      .arst_n(arst_n),
      .H_IN_rsc_mgc_in_wire_d(H_IN_rsc_mgc_in_wire_d),
      .S_IN_rsc_mgc_in_wire_d(S_IN_rsc_mgc_in_wire_d),
      .V_IN_rsc_mgc_in_wire_d(V_IN_rsc_mgc_in_wire_d),
      .R_OUT_rsc_mgc_out_stdreg_d(R_OUT_rsc_mgc_out_stdreg_d),
      .B_OUT_rsc_mgc_out_stdreg_d(B_OUT_rsc_mgc_out_stdreg_d)
    );
endmodule



